name: OctoEverywhere Elegoo Connect
version: "1.0.0"
slug: octoeverywhere_elegoo_connect
description: OctoEverywhere Companion in Elegoo Mode
startup: services
boot: auto
host_network: true
options:
  printer_ip: "192.168.178.33"
schema:
  printer_ip: str
arch:
  - amd64
  - aarch64
